name: ebird
channels:
  - anaconda
  - defaults
dependencies:
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bs4=4.13.4
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - certifi=2025.8.3
  - charset-normalizer=3.3.2
  - expat=2.7.1
  - idna=3.7
  - libcxx=19.1.7
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy=2.3.1
  - numpy-base=2.3.1
  - openssl=3.0.17
  - pandas=2.3.1
  - pip=25.2
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - readline=8.3
  - requests=2.32.4
  - setuptools=72.1.0
  - six=1.17.0
  - soupsieve=2.5
  - sqlite=3.50.2
  - tk=8.6.15
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.3.0
  - wheel=0.45.1
  - xlsxwriter=3.2.3
  - xz=5.6.4
  - zlib=1.2.13
prefix: /opt/miniconda3/envs/ebird
